version: '3'
services:
  app:
    image: openjdk:10
    container_name: sample-app
    ports:
      - 8090:8089
    volumes:
      - .:/app
      - ~/.config/:/root/.config
    working_dir: /app
    command: ./gradlew bootRun
